SurveyMonkey/pyteamcity

README.md
See https://github.com/msabramo/pyteamcity/blob/README_add_travis_badge/README.md
=> README.md: Add PyPI and Travis CI badges

pyteamcity.py
Fix for https://github.com/SurveyMonkey/pyteamcity/pull/11/files#r25622896
Cc: @aconrad
=> Hide internal methods: _get_all_builds[_locator]

pyteamcity.py
=> Add create_project and _put methods

pyteamcity.py, test_pyteamcity.py
Added new locators
* since_build
* until_build
* since_date
* until_date
=> Add new locators

pyteamcity.py, test_pyteamcity.py
Added a simple `get_agent_by_agent_name` method.
I'm also thinking about adding locator support here.
=> Added get_agent_by_agent_name method

pyteamcity.py
Thanks to @sridharavinash for sending a PR (#22).
=> Add get_project_params method

pyteamcity.py
Thanks to @sridharavinash for sending a PR (#22).
=> Add reset_build_counter method

pyteamcity.py, test_pyteamcity.py
Amending #25 from @lpatrick. Thanks, @lpatrick!
=> fixed problem where non-json content type is coerced into json

pyteamcity.py, test_pyteamcity.py
Inspired by #26 from @aletourneau
=> Allow filtering get_builds by pinned

pyteamcity/future/__init__.py, pyteamcity/future/queued_build.py
This allows canceling queued builds, as described at https://confluence.jetbrains.com/display/TCD10/REST+API#RESTAPI-BuildCanceling/Stopping
=> Add QueuedBuild.cancel

pyteamcity/future/teamcity.py, pyteamcity/future/tests/unit/test_build.py, tox.ini
=> Add some responses-based tests for build

pyteamcity/future/build.py, pyteamcity/future/teamcity.py, pyteamcity/future/tests/unit/test_build.py, pyteamcity/future/tests/unit/test_teamcity.py
with unit tests! (using the [`responses`](https://github.com/getsentry/responses) module)
=> Add Build.{pin,unpin}

pyteamcity/future/tests/unit/test_build.py
This gets coverage of `pyteamcity/future/build.py` to:
```
pyteamcity/future/build.py                            136      2    99%   61, 116
```
=> Add more build tests

pyteamcity/future/tests/unit/test_user.py
Gets coverage of `pyteamcity/future/user.py` to 100%! :smile:
=> Add more user tests

pyteamcity/future/tests/unit/test_user_group.py
Gets coverage of `pyteamcity/future/user_group.py` to 100%! :smile:
=> Add user_group tests

pyteamcity/future/tests/unit/test_vcs_root.py
Gets coverage of `pyteamcity/future/vcs_root.py` to 100%! :smile:
=> Add vcs_root tests

pyteamcity/future/tests/unit/test_teamcity.py
Gets coverage of `pyteamcity/future/teamcity.py` to 99%! :smile:
=> Add server_info test

pyteamcity/future/tests/unit/test_queued_build.py
Increases test coverage to:
```
pyteamcity/future/queued_build.py                     104     48    54%   31-32, 45-47, 73-83, 86-98, 120, 122, 124, 128, 141-160, 166-193
```
=> Add test_unit_queued_build_with_responses

pyteamcity/future/tests/unit/test_queued_build.py
Mostly by testing triggering of builds
Increases coverage to:
```
pyteamcity/future/queued_build.py                     101      5    95%   83-95
```
=> Increase coverage for queued_build.py

pyteamcity/future/queued_build.py, pyteamcity/future/tests/unit/test_queued_build.py
This gets coverage of `queued_build.py` to 100%!
```
pyteamcity/future/queued_build.py                     101      0   100%
```
=> Test canceling a queued build

pyteamcity/future/tests/unit/test_teamcity.py
Gets coverage of `teamcity.py` to 100%!
```
pyteamcity/future/teamcity.py                          80      0   100%
```
=> Add test_unit_server_info_exception_with_responses

pyteamcity/future/project.py, pyteamcity/future/tests/unit/test_project.py
Gets coverage of `project.py` to 100%!
```
pyteamcity/future/project.py                           80      0   100%
```
=> Increase project.py test coverage

pyteamcity/future/artifact.py, pyteamcity/future/tests/unit/test_artifact.py
```
pyteamcity/future/artifact.py                          73      0   100%
```
=> 100% coverage of artifact.py

pyteamcity/future/build_type.py, pyteamcity/future/tests/unit/test_build_type.py
```
pyteamcity/future/build_type.py                        74      0   100%
```
=> 100% coverage of build_type.py

pyteamcity/future/tests/unit/test_agent_pool.py
```
...
pyteamcity/future/agent_pool.py                        36      0   100%
...
TOTAL                                                2265    111    95%
```
=> 100% coverage of agent_pool.py

pyteamcity/future/agent.py, pyteamcity/future/tests/unit/test_agent.py, pyteamcity/future/tests/unit/test_teamcity.py
and overall coverage to 96%
```
...
pyteamcity/future/agent.py                             74      1    99%   59
...
TOTAL                                                2286     96    96%
```
=> Get coverage of agent.py to 100%

pyteamcity/future/build.py
for handling `buildType` in data dict.
so I don't have to cover this code with tests.
```
...
pyteamcity/future/build.py                            133      0   100%
...
TOTAL                                                2289     92    96%
```
=> Build.build_type: Remove unused code

pyteamcity/future/change.py, pyteamcity/future/teamcity.py, pyteamcity/future/tests/unit/test_change.py
```
pyteamcity/future/change.py                            38      0   100%
```
=> Add support for querying for changes

README.md, sample.py
=> get_all_projects => get_projects

pyteamcity/future/tests/unit/test_vcs_root.py, pyteamcity/future/vcs_root.py
```
...
pyteamcity/future/vcs_root.py                          56      0   100%
...
TOTAL                                                2515     92    96%
```
=> Add ability to create and delete VCS roots

pyteamcity/future/artifact.py, pyteamcity/future/build.py, pyteamcity/future/build_type.py, pyteamcity/future/core/utils.py, pyteamcity/future/exceptions.py, pyteamcity/future/project.py, pyteamcity/future/queued_build.py, pyteamcity/future/teamcity.py, pyteamcity/future/tests/unit/test_build.py, pyteamcity/future/vcs_root.py, setup.py
Hello @msabramo,
Nice work on the future API. It is shaping up great :+1: 
Here's a somewhat random collection of fixes and feature implementations. Please let me know if you're interested in any of them and if you'll need them packaged as separate PRs. I hope to be able to contribute more, but time for open-source projects has been scarce lately :(
Kind regards,
Georgi
=> Assorted fixes and features
